services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main    
    environment:
      - WEBUI_AUTH=False
    ports:
      # Change port 3104 to whatever port you need
      - 3104:8080
    volumes:
      - ./data:/app/backend/data